<?php
namespace Ksfraser\FaBankImport\Views;

use Ksfraser\HTML\HtmlElementInterface;

/**
 * Customer Partner Type View
 * 
 * Single Responsibility: Display customer/branch selection UI for a bank transaction line item.
 * 
 * Displays:
 * - "From Customer/Branch:" label
 * - Customer dropdown list
 * 
 * @author Kevin Fraser
 * @since 20250422
 */
class CustomerPartnerTypeView implements HtmlElementInterface
{
    private $lineItemId;
    
    /**
     * Constructor
     * 
     * @param int $lineItemId The ID of the line item
     */
    public function __construct(int $lineItemId)
    {
        $this->lineItemId = $lineItemId;
    }
    
    /**
     * Get the HTML for this view
     * 
     * @return string HTML output
     */
    public function getHtml(): string
    {
        // This view depends on customer data being available in POST
        // The actual customer list is generated by the customer_list() function
        // which reads from $_POST['customerListData']
        ob_start();
        
        // Display customer/branch selection
        label_row(
            _("From Customer/Branch:"),
            customer_list("partnerId_{$this->lineItemId}")
        );
        
        return ob_get_clean();
    }
    
    /**
     * Output HTML directly (for legacy compatibility)
     */
    public function toHtml(): void
    {
        echo $this->getHtml();
    }
}