<?php

if (!defined('ST_JOURNAL')) define('ST_JOURNAL', 0);
if (!defined('ST_BANKPAYMENT')) define('ST_BANKPAYMENT', 2);
if (!defined('ST_BANKDEPOSIT')) define('ST_BANKDEPOSIT', 3);
if (!defined('ST_BANKTRANSFER')) define('ST_BANKTRANSFER', 4);
if (!defined('ST_SALESINVOICE')) define('ST_SALESINVOICE', 10);
if (!defined('ST_CUSTCREDIT')) define('ST_CUSTCREDIT', 11);
if (!defined('ST_CUSTPAYMENT')) define('ST_CUSTPAYMENT', 12);
if (!defined('ST_CUSTDELIVERY')) define('ST_CUSTDELIVERY', 13);
if (!defined('ST_LOCTRANSFER')) define('ST_LOCTRANSFER', 16);
if (!defined('ST_PURCHORDER')) define('ST_PURCHORDER', 18);
if (!defined('ST_SUPPINVOICE')) define('ST_SUPPINVOICE', 20);
if (!defined('ST_SUPPCREDIT')) define('ST_SUPPCREDIT', 21);
if (!defined('ST_SUPPAYMENT')) define('ST_SUPPAYMENT', 22);
if (!defined('ST_SUPPRECEIVE')) define('ST_SUPPRECEIVE', 25);
if (!defined('ST_WORKORDER')) define('ST_WORKORDER', 26);
if (!defined('ST_MANUISSUE')) define('ST_MANUISSUE', 28);
if (!defined('ST_MANURECEIVE')) define('ST_MANURECEIVE', 29);
if (!defined('ST_SALESORDER')) define('ST_SALESORDER', 30);
if (!defined('ST_SALESQUOTE')) define('ST_SALESQUOTE', 32);
if (!defined('ST_INVADJUST')) define('ST_INVADJUST', 35);
if (!defined('ST_COSTUPDATE')) define('ST_COSTUPDATE', 40);
if (!defined('ST_DIMENSION')) define('ST_DIMENSION', 50);
