flowchart LR
  PROD_process_statements_php -- use --> symbol_Ksfraser_FaBankImport_views_ProcessStatementsView
  PROD_process_statements_php -- require --> PROD_Views_module_menu_view_php
  PROD_process_statements_php -- require --> PROD_class_bank_import_controller_php
  PROD_process_statements_php -- require --> ksf_modules_common_class_fa_bank_transfer_php
  PROD_process_statements_php -- require --> PROD_src_Ksfraser_FaBankImport_header_table_php
  PROD_process_statements_php -- require --> PROD_class_bi_transactions_php
  PROD_src_Ksfraser_Controller_BiLineItemController_php -- use --> symbol_Ksfraser_common_GenericFaInterface
  PROD_src_Ksfraser_Controller_BiLineItemController_php -- use --> symbol_Ksfraser_common_Defines
  PROD_src_Ksfraser_Controller_BiLineItemController_php -- use --> symbol_Ksfraser_FaBankImport_Model_BiLineItemModel
  PROD_src_Ksfraser_Controller_BiLineItemController_php -- use --> symbol_Ksfraser_FaBankImport_View_BiLineItemView
  PROD_src_Ksfraser_FaBankImport_Views_BiLineItemView_php -- use --> symbol_Ksfraser_FaBankImport_Model_BiLineItemModel
  PROD_src_Ksfraser_FaBankImport_controller_BiLineItemController_php -- use --> symbol_Ksfraser_FaBankImport_Model_BiLineItemModel
  PROD_src_Ksfraser_FaBankImport_controller_BiLineItemController_php -- use --> symbol_Ksfraser_FaBankImport_View_BiLineItemView
  PROD_src_Ksfraser_FaBankImport_controllers_BiLineItemController_php -- use --> symbol_Ksfraser_FaBankImport_Model_BiLineItemModel
  PROD_src_Ksfraser_FaBankImport_controllers_BiLineItemController_php -- use --> symbol_Ksfraser_FaBankImport_View_BiLineItemView
  PROD_src_Ksfraser_FaBankImport_model_BiLineItemModel_php -- use --> symbol_Ksfraser_common_GenericFaInterface
  PROD_src_Ksfraser_FaBankImport_model_BiLineItemModel_php -- use --> symbol_Ksfraser_frontaccounting_FaBankAccounts
  PROD_src_Ksfraser_FaBankImport_model_BiLineItemModel_php -- use --> symbol_Ksfraser_frontaccounting_FaCustomerPayment
  PROD_src_Ksfraser_FaBankImport_model_BiLineItemModel_php -- use --> symbol_Ksfraser_frontaccounting_FaGl
  PROD_src_Ksfraser_FaBankImport_models_BiLineItemModel_php -- use --> symbol_Ksfraser_common_GenericFaInterface
  PROD_src_Ksfraser_FaBankImport_models_BiLineItemModel_php -- use --> symbol_Ksfraser_frontaccounting_FaBankAccounts
  PROD_src_Ksfraser_FaBankImport_models_BiLineItemModel_php -- use --> symbol_Ksfraser_frontaccounting_FaCustomerPayment
  PROD_src_Ksfraser_FaBankImport_models_BiLineItemModel_php -- use --> symbol_Ksfraser_frontaccounting_FaGl
  PROD_src_Ksfraser_FaBankImport_view_BiLineItemView_php -- use --> symbol_Ksfraser_FaBankImport_Model_BiLineItemModel
  PROD_src_Ksfraser_FaBankImport_views_BiLineItemView_php -- use --> symbol_Ksfraser_FaBankImport_Model_BiLineItemModel
  PROD_src_Ksfraser_FaBankImport_views_ProcessStatementsView_php -- require --> PROD_src_Ksfraser_FaBankImport_views_class_bi_lineitem_php
  PROD_src_Ksfraser_Model_BiLineItemModel_php -- use --> symbol_Ksfraser_common_GenericFaInterface
  PROD_src_Ksfraser_Model_BiLineItemModel_php -- use --> symbol_Ksfraser_frontaccounting_FaBankAccounts
  PROD_src_Ksfraser_Model_BiLineItemModel_php -- use --> symbol_Ksfraser_frontaccounting_FaCustomerPayment
  PROD_src_Ksfraser_Model_BiLineItemModel_php -- use --> symbol_Ksfraser_frontaccounting_FaGl
  PROD_src_Ksfraser_Model_BiLineItemModel_php -- use --> symbol_Ksfraser_frontaccounting_FaBankAccounts
  PROD_src_Ksfraser_Model_BiLineItemModel_php -- use --> symbol_Ksfraser_frontaccounting_FaGl
  PROD_src_Ksfraser_Model_BiLineItemModel_php -- require --> PROD_src_Ksfraser_ksf_modules_common_class_fa_bank_accounts_php
  PROD_src_Ksfraser_Model_BiLineItemModel_php -- require --> PROD_src_Ksfraser_Model_class_bi_transactions_php
  PROD_src_Ksfraser_View_BiLineItemView_php -- use --> symbol_Ksfraser_FaBankImport_Model_BiLineItemModel
  PROD_tests_integration_BiLineItemModelProductionBaselineTest_php -- use --> symbol_PHPUnit_Framework_TestCase
  PROD_tests_integration_ProcessStatementsViewRefactoringTest_php -- use --> symbol_PHPUnit_Framework_TestCase
  PROD_tests_integration_ProcessStatementsViewRefactoringTest_php -- require --> PROD_tests_integration_header_table_php
  PROD_tests_integration_ProcessStatementsViewRefactoringTest_php -- require --> PROD_tests_integration_src_Ksfraser_FaBankImport_Views_ProcessStatementsView_php
  PROD_tests_integration_ProcessStatementsViewRefactoringTest_php -- require --> PROD_tests_integration_src_Ksfraser_FaBankImport_Views_ProcessStatementsView_php
  PROD_tests_unit_views_ProcessStatementsViewTest_php -- use --> symbol_PHPUnit_Framework_TestCase
  PROD_tests_unit_views_ProcessStatementsViewTest_php -- use --> symbol_Ksfraser_FaBankImport_Views_ProcessStatementsView
  process_statements_php -- use --> symbol_Ksfraser_FaBankImport_views_ProcessStatementsView
  process_statements_php -- require --> Views_module_menu_view_php
  process_statements_php -- require --> class_bank_import_controller_php
  process_statements_php -- require --> ___ksf_modules_common_class_fa_bank_transfer_php
  process_statements_php -- require --> src_Ksfraser_FaBankImport_header_table_php
  process_statements_php -- require --> class_bi_transactions_php
  process_statements_php -- require --> class_bi_lineitem_php
  src_Ksfraser_Controller_BiLineItemController_php -- use --> symbol_Ksfraser_common_GenericFaInterface
  src_Ksfraser_Controller_BiLineItemController_php -- use --> symbol_Ksfraser_common_Defines
  src_Ksfraser_Controller_BiLineItemController_php -- use --> symbol_Ksfraser_FaBankImport_Model_BiLineItemModel
  src_Ksfraser_Controller_BiLineItemController_php -- use --> symbol_Ksfraser_FaBankImport_View_BiLineItemView
  src_Ksfraser_FaBankImport_controller_BiLineItemController_php -- use --> symbol_Ksfraser_FaBankImport_Model_BiLineItemModel
  src_Ksfraser_FaBankImport_controller_BiLineItemController_php -- use --> symbol_Ksfraser_FaBankImport_View_BiLineItemView
  src_Ksfraser_FaBankImport_controllers_BiLineItemController_php -- use --> symbol_Ksfraser_FaBankImport_Model_BiLineItemModel
  src_Ksfraser_FaBankImport_controllers_BiLineItemController_php -- use --> symbol_Ksfraser_FaBankImport_View_BiLineItemView
  src_Ksfraser_FaBankImport_model_BiLineItemModel_php -- use --> symbol_Ksfraser_common_GenericFaInterface
  src_Ksfraser_FaBankImport_model_BiLineItemModel_php -- use --> symbol_Ksfraser_frontaccounting_FaBankAccounts
  src_Ksfraser_FaBankImport_model_BiLineItemModel_php -- use --> symbol_Ksfraser_frontaccounting_FaCustomerPayment
  src_Ksfraser_FaBankImport_model_BiLineItemModel_php -- use --> symbol_Ksfraser_frontaccounting_FaGl
  src_Ksfraser_FaBankImport_models_BiLineItemModel_php -- use --> symbol_Ksfraser_common_GenericFaInterface
  src_Ksfraser_FaBankImport_models_BiLineItemModel_php -- use --> symbol_Ksfraser_frontaccounting_FaBankAccounts
  src_Ksfraser_FaBankImport_models_BiLineItemModel_php -- use --> symbol_Ksfraser_frontaccounting_FaCustomerPayment
  src_Ksfraser_FaBankImport_models_BiLineItemModel_php -- use --> symbol_Ksfraser_frontaccounting_FaGl
  src_Ksfraser_FaBankImport_view_BiLineItemView_php -- use --> symbol_Ksfraser_FaBankImport_Model_BiLineItemModel
  src_Ksfraser_FaBankImport_views_BiLineItemView_php -- use --> symbol_Ksfraser_FaBankImport_Model_BiLineItemModel
  src_Ksfraser_FaBankImport_views_ProcessStatementsView_php -- require --> src_Ksfraser_FaBankImport_views_class_bi_lineitem_php
  src_Ksfraser_Model_BiLineItemModel_php -- use --> symbol_Ksfraser_common_GenericFaInterface
  src_Ksfraser_Model_BiLineItemModel_php -- use --> symbol_Ksfraser_frontaccounting_FaBankAccounts
  src_Ksfraser_Model_BiLineItemModel_php -- use --> symbol_Ksfraser_frontaccounting_FaCustomerPayment
  src_Ksfraser_Model_BiLineItemModel_php -- use --> symbol_Ksfraser_frontaccounting_FaGl
  src_Ksfraser_Model_BiLineItemModel_php -- use --> symbol_Ksfraser_frontaccounting_FaBankAccounts
  src_Ksfraser_Model_BiLineItemModel_php -- use --> symbol_Ksfraser_frontaccounting_FaGl
  src_Ksfraser_Model_BiLineItemModel_php -- require --> src_Ksfraser_ksf_modules_common_class_fa_bank_accounts_php
  src_Ksfraser_Model_BiLineItemModel_php -- require --> src_Ksfraser_Model_class_bi_transactions_php
  src_Ksfraser_View_BiLineItemView_php -- use --> symbol_Ksfraser_FaBankImport_Model_BiLineItemModel
  tests_Views_ProcessStatementsViewTest_php -- use --> symbol_Ksfraser_FaBankImport_Views_ProcessStatementsView
  tests_Views_ProcessStatementsViewTest_php -- use --> symbol_PHPUnit_Framework_TestCase
  tests_integration_BiLineItemModelProductionBaselineTest_php -- use --> symbol_PHPUnit_Framework_TestCase
  tests_integration_ProcessStatementsViewRefactoringTest_php -- use --> symbol_PHPUnit_Framework_TestCase
  tests_integration_ProcessStatementsViewRefactoringTest_php -- require --> tests_integration_header_table_php
  tests_integration_ProcessStatementsViewRefactoringTest_php -- require --> tests_integration_src_Ksfraser_FaBankImport_Views_ProcessStatementsView_php
  tests_integration_ProcessStatementsViewRefactoringTest_php -- require --> tests_integration_src_Ksfraser_FaBankImport_Views_ProcessStatementsView_php
  tests_unit_BiTransactionsPaginationTest_php -- use --> symbol_PHPUnit_Framework_TestCase
  tests_unit_views_ProcessStatementsViewTest_php -- use --> symbol_PHPUnit_Framework_TestCase
  tests_unit_views_ProcessStatementsViewTest_php -- use --> symbol_Ksfraser_FaBankImport_Views_ProcessStatementsView
  class_bank_import_controller_php -- use --> symbol_Ksfraser_FaBankImport_Handlers_AddVendor
  class_bank_import_controller_php -- require --> ___ksf_modules_common_class_origin_php
  class_bank_import_controller_php -- require --> class_bi_transaction_php
  class_bank_import_controller_php -- require --> class_bi_transactions_php
  class_bank_import_controller_php -- require --> includes_pdata_inc
  class_bank_import_controller_php -- require --> ___ksf_modules_common_class_fa_bank_transfer_php
  ___ksf_modules_common_class_fa_bank_transfer_php -- require --> ___ksf_modules_common_class_fa_origin_php
  ___ksf_modules_common_class_fa_bank_transfer_php -- require --> ___ksf_modules_common_class_VIEW_php
  src_Ksfraser_FaBankImport_header_table_php -- require --> src_Ksfraser_ksf_modules_common_class_fa_bank_transfer_php
  class_bi_lineitem_php -- use --> symbol_KsfBankImport_Views_ViewFactory
  class_bi_lineitem_php -- use --> symbol_Ksfraser_SettledTransactionDisplay
  class_bi_lineitem_php -- use --> symbol_Ksfraser_Views_CommentSubmitView
  class_bi_lineitem_php -- use --> symbol_Ksfraser_Views_PartnerTypeSelectorView
  class_bi_lineitem_php -- use --> symbol_Ksfraser_HTML_Composites_HTML_ROW
  class_bi_lineitem_php -- use --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_bi_lineitem_php -- use --> symbol_Ksfraser_HTML_Elements__HtmlOB__HtmlRaw__HtmlTable__HtmlTd__HtmlTableRow__HtmlLink__HtmlA_
  class_bi_lineitem_php -- use --> symbol_Ksfraser_HTML__HtmlElement__HtmlAttribute__HtmlFragment_
  class_bi_lineitem_php -- use --> symbol_Ksfraser_HTML_Composites_HTML_ROW_LABEL
  class_bi_lineitem_php -- use --> symbol_Ksfraser_PartnerFormData
  class_bi_lineitem_php -- use --> symbol_Ksfraser_FaBankImport_models_BankAccountByNumber
  class_bi_lineitem_php -- use --> symbol_Ksfraser_FaBankImport_models_MatchingJEs
  class_bi_lineitem_php -- require --> class_bi_transactions_php
  ___ksf_modules_common_class_origin_php -- require --> defines_inc_php
  class_bi_transaction_php -- require --> class_bi_transactions_php
  ___ksf_modules_common_class_fa_origin_php -- require --> class_origin_php
  ___ksf_modules_common_class_VIEW_php -- require --> class_origin_php