flowchart LR
  build_partner_keyword_data_php -- ref --> symbol_Ksfraser_FaBankImport_Config_ConfigService
  build_partner_keyword_data_php -- ref --> symbol_Ksfraser_FaBankImport_Config_ConfigService
  class_bank_import_controller_php -- use --> symbol_Ksfraser_FaBankImport_Handlers_AddVendor
  class_bank_import_controller_php -- require --> ___ksf_modules_common_class_origin_php
  class_bank_import_controller_php -- require --> class_bi_transaction_php
  class_bank_import_controller_php -- require --> class_bi_transactions_php
  class_bank_import_controller_php -- require --> includes_pdata_inc
  class_bank_import_controller_php -- require --> ___ksf_modules_common_class_fa_bank_transfer_php
  class_bank_import_controller_php -- new --> symbol_bi_transaction
  class_bank_import_controller_php -- new --> symbol_bi_transactions_model
  class_bank_import_controller_php -- new --> symbol_bi_transaction
  class_bank_import_controller_php -- new --> symbol_bi_transactions_model
  class_bank_import_controller_php -- new --> symbol_customer
  class_bank_import_controller_php -- new --> symbol_vendor
  class_bank_import_controller_php -- new --> symbol_AddVendor
  class_bank_import_controller_php -- new --> symbol_VendorAddedEvent
  class_bank_import_controller_php -- new --> symbol_VendorNotAddedEvent
  class_bank_import_controller_php -- new --> symbol_bi_transactions_model
  class_bank_import_controller_php -- new --> symbol_items_cart
  class_bank_import_controller_php -- new --> symbol_Exception
  class_bank_import_controller_php -- new --> symbol_Exception
  class_bank_import_controller_php -- new --> symbol_Exception
  class_bank_import_controller_php -- new --> symbol_Exception
  class_bank_import_controller_php -- new --> symbol_Exception
  class_bank_import_controller_php -- new --> symbol_Reference
  class_bank_import_controller_php -- new --> symbol_Exception
  class_bank_import_controller_php -- new --> symbol_Reference
  class_bank_import_controller_php -- new --> symbol_items_cart
  class_bank_import_controller_php -- new --> symbol_fa_customer_payment
  class_bank_import_controller_php -- new --> symbol_fa_bank_transfer
  class_bank_import_controller_php -- ref --> symbol_Ksfraser_FaBankImport_Handlers_AddVendor
  class_bank_import_controller_php -- ref --> symbol_View
  class_bank_import_controller_php -- ref --> symbol_View
  class_bank_import_controller_php -- ref --> symbol_View
  class_bank_import_controller_php -- ref --> symbol_View
  class_bank_import_controller_php -- ref --> symbol_View
  class_bank_import_controller_php -- ref --> symbol_View
  class_bank_import_controller_php -- ref --> symbol_View
  class_bi_counterparty_model_php -- require --> ___ksf_modules_commone_class_generic_fa_interface_php
  class_bi_counterparty_model_php -- require --> ___ksf_modules_commone_defines_inc_php
  class_bi_lineitem_php -- use --> symbol_KsfBankImport_Views_ViewFactory
  class_bi_lineitem_php -- use --> symbol_Ksfraser_SettledTransactionDisplay
  class_bi_lineitem_php -- use --> symbol_Ksfraser_Views_CommentSubmitView
  class_bi_lineitem_php -- use --> symbol_Ksfraser_Views_PartnerTypeSelectorView
  class_bi_lineitem_php -- use --> symbol_Ksfraser_HTML_Composites_HTML_ROW
  class_bi_lineitem_php -- use --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_bi_lineitem_php -- use --> symbol_Ksfraser_HTML_Elements__HtmlOB__HtmlRaw__HtmlTable__HtmlTd__HtmlTableRow__HtmlLink__HtmlA_
  class_bi_lineitem_php -- use --> symbol_Ksfraser_HTML__HtmlElement__HtmlAttribute__HtmlFragment_
  class_bi_lineitem_php -- use --> symbol_Ksfraser_HTML_Composites_HTML_ROW_LABEL
  class_bi_lineitem_php -- use --> symbol_Ksfraser_PartnerFormData
  class_bi_lineitem_php -- use --> symbol_Ksfraser_FaBankImport_models_BankAccountByNumber
  class_bi_lineitem_php -- use --> symbol_Ksfraser_FaBankImport_models_MatchingJEs
  class_bi_lineitem_php -- require --> class_bi_transactions_php
  class_bi_lineitem_php -- new --> symbol_PartnerFormData
  class_bi_lineitem_php -- new --> symbol_TransactionTypeLabel
  class_bi_lineitem_php -- new --> symbol_HtmlFragment
  class_bi_lineitem_php -- new --> symbol_HtmlTableRow
  class_bi_lineitem_php -- new --> symbol_BankAccountByNumber
  class_bi_lineitem_php -- new --> symbol_TransDate
  class_bi_lineitem_php -- new --> symbol_TransType
  class_bi_lineitem_php -- new --> symbol_OurBankAccount
  class_bi_lineitem_php -- new --> symbol_OtherBankAccount
  class_bi_lineitem_php -- new --> symbol_AmountCharges
  class_bi_lineitem_php -- new --> symbol_TransTitle
  class_bi_lineitem_php -- new --> symbol_HtmlOB
  class_bi_lineitem_php -- new --> symbol_HtmlRaw
  class_bi_lineitem_php -- new --> symbol_HtmlTable
  class_bi_lineitem_php -- new --> symbol_HtmlAttribute
  class_bi_lineitem_php -- new --> symbol_HtmlAttribute
  class_bi_lineitem_php -- new --> symbol_HtmlTd
  class_bi_lineitem_php -- new --> symbol_HtmlAttribute
  class_bi_lineitem_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlHidden
  class_bi_lineitem_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlHidden
  class_bi_lineitem_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlHidden
  class_bi_lineitem_php -- new --> symbol_AddVendorButtonRow
  class_bi_lineitem_php -- new --> symbol_AddCustomerButtonRow
  class_bi_lineitem_php -- new --> symbol_Exception
  class_bi_lineitem_php -- new --> symbol_Exception
  class_bi_lineitem_php -- new --> symbol_Exception
  class_bi_lineitem_php -- new --> symbol_bi_transactions_model
  class_bi_lineitem_php -- new --> symbol_MatchingJEs
  class_bi_lineitem_php -- new --> symbol_HtmlA
  class_bi_lineitem_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_bi_lineitem_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlRaw
  class_bi_lineitem_php -- new --> symbol__Ksfraser_HTML_Composites_HtmlLabelRow
  class_bi_lineitem_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_bi_lineitem_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_bi_lineitem_php -- new --> symbol__Ksfraser_HTML_Composites_HtmlLabelRow
  class_bi_lineitem_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlHidden
  class_bi_lineitem_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlHidden
  class_bi_lineitem_php -- new --> symbol_SupplierPartnerTypeView
  class_bi_lineitem_php -- new --> symbol_CustomerPartnerTypeView
  class_bi_lineitem_php -- new --> symbol_BankTransferPartnerTypeView
  class_bi_lineitem_php -- new --> symbol_QuickEntryPartnerTypeView
  class_bi_lineitem_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlHidden
  class_bi_lineitem_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlSelect
  class_bi_lineitem_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlOption
  class_bi_lineitem_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlOption
  class_bi_lineitem_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_bi_lineitem_php -- new --> symbol__Ksfraser_HTML_Composites_HtmlLabelRow
  class_bi_lineitem_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlInput
  class_bi_lineitem_php -- new --> symbol__Ksfraser_HTML_HtmlAttribute
  class_bi_lineitem_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_bi_lineitem_php -- new --> symbol__Ksfraser_HTML_Composites_HtmlLabelRow
  class_bi_lineitem_php -- new --> symbol_PartnerTypeDisplayStrategy
  class_bi_lineitem_php -- new --> symbol_CommentSubmitView
  class_bi_lineitem_php -- new --> symbol_HtmlOB
  class_bi_lineitem_php -- new --> symbol_transaction
  class_bi_lineitem_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_bi_lineitem_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_bi_lineitem_php -- new --> symbol__Ksfraser_HTML_Composites_HtmlLabelRow
  class_bi_lineitem_php -- new --> symbol_PartnerTypeSelectorView
  class_bi_lineitem_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlHidden
  class_bi_lineitem_php -- new --> symbol_HtmlRaw
  class_bi_lineitem_php -- new --> symbol_HtmlTable
  class_bi_lineitem_php -- new --> symbol_HtmlAttribute
  class_bi_lineitem_php -- new --> symbol_HtmlAttribute
  class_bi_lineitem_php -- new --> symbol_HtmlTd
  class_bi_lineitem_php -- new --> symbol_HtmlAttribute
  class_bi_lineitem_php -- new --> symbol_HtmlAttribute
  class_bi_lineitem_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_bi_lineitem_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlSubmit
  class_bi_lineitem_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_bi_lineitem_php -- new --> symbol__Ksfraser_HTML_Composites_HtmlLabelRow
  class_bi_lineitem_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_bi_lineitem_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlSubmit
  class_bi_lineitem_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_bi_lineitem_php -- new --> symbol__Ksfraser_HTML_Composites_HtmlLabelRow
  class_bi_lineitem_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlHidden
  class_bi_lineitem_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlHidden
  class_bi_lineitem_php -- new --> symbol_SettledTransactionDisplay
  class_bi_lineitem_php -- ref --> symbol_View
  class_bi_lineitem_php -- ref --> symbol_View
  class_bi_lineitem_php -- ref --> symbol_SupplierPartnerTypeView
  class_bi_lineitem_php -- ref --> symbol_CustomerPartnerTypeView
  class_bi_lineitem_php -- ref --> symbol_BankTransferPartnerTypeView
  class_bi_lineitem_php -- ref --> symbol_QuickEntryPartnerTypeView
  class_bi_lineitem_php -- ref --> symbol_KsfBankImport_Views_ViewFactory
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_SettledTransactionDisplay
  class_bi_lineitem_php -- ref --> symbol_CommentSubmitView
  class_bi_lineitem_php -- ref --> symbol_CommentSubmitView
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_Views_CommentSubmitView
  class_bi_lineitem_php -- ref --> symbol_PartnerTypeSelectorView
  class_bi_lineitem_php -- ref --> symbol_PartnerTypeSelectorView
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_Views_PartnerTypeSelectorView
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML_Composites_HTML_ROW
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML_Elements
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML_Composites_HTML_ROW_LABEL
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_PartnerFormData
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_FaBankImport_models_BankAccountByNumber
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_FaBankImport_models_MatchingJEs
  class_bi_lineitem_php -- ref --> symbol_View
  class_bi_lineitem_php -- ref --> symbol_View
  class_bi_lineitem_php -- ref --> symbol_View
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlHidden
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlHidden
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlHidden
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlRaw
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML_Composites_HtmlLabelRow
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML_Composites_HtmlLabelRow
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlHidden
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlHidden
  class_bi_lineitem_php -- ref --> symbol_SupplierPartnerTypeView
  class_bi_lineitem_php -- ref --> symbol_SupplierPartnerTypeView
  class_bi_lineitem_php -- ref --> symbol_CustomerPartnerTypeView
  class_bi_lineitem_php -- ref --> symbol_CustomerPartnerTypeView
  class_bi_lineitem_php -- ref --> symbol_BankTransferPartnerTypeView
  class_bi_lineitem_php -- ref --> symbol_BankTransferPartnerTypeView
  class_bi_lineitem_php -- ref --> symbol_QuickEntryPartnerTypeView
  class_bi_lineitem_php -- ref --> symbol_QuickEntryPartnerTypeView
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlHidden
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_FrontAccounting_TransactionTypes_TransactionTypesRegistry
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlSelect
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlOption
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlOption
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML_Composites_HtmlLabelRow
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlInput
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML_HtmlAttribute
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML_Composites_HtmlLabelRow
  class_bi_lineitem_php -- ref --> symbol_CommentSubmitView
  class_bi_lineitem_php -- ref --> symbol_CommentSubmitView
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML_Composites_HtmlLabelRow
  class_bi_lineitem_php -- ref --> symbol_PartnerTypeSelectorView
  class_bi_lineitem_php -- ref --> symbol_PartnerTypeSelectorView
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlHidden
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlSubmit
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML_Composites_HtmlLabelRow
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlSubmit
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML_Composites_HtmlLabelRow
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlHidden
  class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlHidden
  class_bi_partners_data_php -- ref --> symbol_SHOPPERS_nSHOPPERS_n
  class_bi_statements_php -- require --> ___ksf_modules_common_class_generic_fa_interface_php
  class_bi_statements_php -- require --> ___ksf_modules_common_defines_inc_php
  class_bi_statements_php -- new --> symbol_Exception
  class_bi_statements_php -- new --> symbol_Exception
  class_bi_statements_php -- new --> symbol_Exception
  class_bi_statements_php -- ref --> symbol_Model
  class_bi_transaction_php -- require --> class_bi_transactions_php
  class_bi_transactions_php -- new --> symbol_Exception
  class_bi_transactions_php -- new --> symbol__KsfBankImport_Services_TransactionFilterService
  class_bi_transactions_php -- new --> symbol__Ksfraser_FaBankImport_Service_TransactionCounter
  class_bi_transactions_php -- new --> symbol_offset
  class_bi_transactions_php -- new --> symbol__Ksfraser_FaBankImport_Results_PaginatedTransactionResult
  class_bi_transactions_php -- new --> symbol_Exception
  class_bi_transactions_php -- new --> symbol_Exception
  class_bi_transactions_php -- new --> symbol_Exception
  class_bi_transactions_php -- new --> symbol_Exception
  class_bi_transactions_php -- new --> symbol_Exception
  class_bi_transactions_php -- new --> symbol_Exception
  class_bi_transactions_php -- new --> symbol_Exception
  class_bi_transactions_php -- new --> symbol_Exception
  class_bi_transactions_php -- new --> symbol_Exception
  class_bi_transactions_php -- ref --> symbol_Ksfraser_FaBankImport_Results_PaginatedTransactionResult
  class_bi_transactions_php -- ref --> symbol_KsfBankImport_Services_TransactionFilterService
  class_bi_transactions_php -- ref --> symbol_Ksfraser_FaBankImport_Service_TransactionCounter
  class_bi_transactions_php -- ref --> symbol_Ksfraser_FaBankImport_Results_PaginatedTransactionResult
  class_bi_transactions_refactored_example_php -- use --> symbol_Ksfraser_FaBankImport_Database_TransactionQueryBuilder
  class_bi_transactions_refactored_example_php -- use --> symbol_Ksfraser_FaBankImport_Database_TransactionRepository
  class_bi_transactions_refactored_example_php -- new --> symbol_TransactionQueryBuilder
  class_bi_transactions_refactored_example_php -- new --> symbol_TransactionRepository
  class_bi_transactions_refactored_example_php -- new --> symbol_bi_transactions_model_refactored
  class_bi_transactions_refactored_example_php -- new --> symbol_Exception
  class_bi_transactions_refactored_example_php -- new --> symbol_query
  class_bi_transactions_refactored_example_php -- new --> symbol_queries
  class_bi_transactions_refactored_example_php -- new --> symbol_architecture
  class_bi_transactions_refactored_example_php -- new --> symbol_implementation
  class_bi_transactions_refactored_example_php -- new --> symbol_class
  class_bi_transactions_refactored_example_php -- ref --> symbol_Ksfraser_FaBankImport_Database_TransactionQueryBuilder
  class_bi_transactions_refactored_example_php -- ref --> symbol_Ksfraser_FaBankImport_Database_TransactionRepository
  class_bi_transactions_refactored_example_php -- ref --> symbol_Model
  class_bi_transactions_refactored_example_php -- ref --> symbol_Model
  class_bi_transactionTitle_model_php -- use --> symbol_Ksfraser_common_GenericFaInterface
  class_bi_transactionTitle_model_php -- use --> symbol_Ksfraser_common_Defines
  class_bi_transactionTitle_model_php -- require --> ___ksf_modules_commone_class_generic_fa_interface_php
  class_bi_transactionTitle_model_php -- require --> ___ksf_modules_commone_defines_inc_php
  class_bi_transactionTitle_model_php -- ref --> symbol_Ksfraser_common_GenericFaInterface
  class_bi_transactionTitle_model_php -- ref --> symbol_Ksfraser_common_Defines
  class_transactions_table_php -- new --> symbol_transaction_table_row
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlTable
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlTableRow
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlTableCell
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlTable
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlSubmit
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlHidden
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlHidden
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlHidden
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlTableCell
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlTable
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlSubmit
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- new --> symbol_transaction
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlHidden
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlHidden
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlSelect
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- new --> symbol__Ksfraser_SupplierDataProvider
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- new --> symbol__Ksfraser_CustomerDataProvider
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlHidden
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- new --> symbol__Ksfraser_BankAccountDataProvider
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- new --> symbol__Ksfraser_QuickEntryDataProvider
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlHidden
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlSelect
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlHidden
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlHidden
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlHidden
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlHidden
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlHidden
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlHidden
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlSubmit
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- new --> symbol__Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlTable
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlTableRow
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlTableCell
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlTable
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlSubmit
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlHidden
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlHidden
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlHidden
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlTableCell
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlTable
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlSubmit
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlHidden
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlHidden
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlSelect
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- ref --> symbol_Ksfraser_SupplierDataProvider
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- ref --> symbol_Ksfraser_CustomerDataProvider
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlHidden
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- ref --> symbol_Ksfraser_BankAccountDataProvider
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- ref --> symbol_Ksfraser_QuickEntryDataProvider
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlHidden
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlSelect
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlHidden
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlHidden
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlHidden
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlHidden
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlHidden
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlHidden
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlSubmit
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Composites_HtmlLabelRow
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_transactions_table_php -- ref --> symbol_Ksfraser_HTML_Composites_HtmlLabelRow
  class_ViewBiLineItems_php -- new --> symbol_code
  class_ViewBiLineItems_php -- new --> symbol_ViewBILineItems
  class_ViewBiLineItems_php -- new --> symbol_HTML_TABLE
  class_ViewBiLineItems_php -- new --> symbol_TransDate
  class_ViewBiLineItems_php -- new --> symbol_TransType
  class_ViewBiLineItems_php -- new --> symbol_OurBankAccount
  class_ViewBiLineItems_php -- new --> symbol_OtherBankAccount
  class_ViewBiLineItems_php -- new --> symbol_AmountCharges
  class_ViewBiLineItems_php -- new --> symbol_TransTitle
  class_ViewBiLineItems_php -- new --> symbol__Ksfraser_HTML_HtmlFragment
  class_ViewBiLineItems_php -- new --> symbol__Ksfraser_HTML_HtmlFragment
  class_ViewBiLineItems_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlHidden
  class_ViewBiLineItems_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_ViewBiLineItems_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlString
  class_ViewBiLineItems_php -- new --> symbol__Ksfraser_HTML_Composites_HtmlLabelRow
  class_ViewBiLineItems_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlHidden
  class_ViewBiLineItems_php -- new --> symbol__Ksfraser_HTML_Elements_HtmlHidden
  class_ViewBiLineItems_php -- new --> symbol_AddCustomerButtonRow
  class_ViewBiLineItems_php -- new --> symbol_AddVendorButtonRow
  class_ViewBiLineItems_php -- new --> symbol_HtmlString
  class_ViewBiLineItems_php -- new --> symbol_HtmlAttribute
  class_ViewBiLineItems_php -- new --> symbol_HtmlAttribute
  class_ViewBiLineItems_php -- new --> symbol_CustomerTransactionDetails
  class_ViewBiLineItems_php -- new --> symbol_fa_customer_payment
  class_ViewBiLineItems_php -- new --> symbol__Ksfraser_HTML_HtmlFragment
  class_ViewBiLineItems_php -- new --> symbol_ProcessTransactionButtonRow
  class_ViewBiLineItems_php -- new --> symbol_transaction
  class_ViewBiLineItems_php -- new --> symbol_ToggleTransactionRow
  class_ViewBiLineItems_php -- new --> symbol_UnsetTransButtonRow
  class_ViewBiLineItems_php -- ref --> symbol_View
  class_ViewBiLineItems_php -- ref --> symbol_Ksfraser_HTML_HtmlFragment
  class_ViewBiLineItems_php -- ref --> symbol_Ksfraser_HTML_HtmlElementInterface
  class_ViewBiLineItems_php -- ref --> symbol_Ksfraser_HTML_HtmlFragment
  class_ViewBiLineItems_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlHidden
  class_ViewBiLineItems_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_ViewBiLineItems_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlString
  class_ViewBiLineItems_php -- ref --> symbol_Ksfraser_HTML_Composites_HtmlLabelRow
  class_ViewBiLineItems_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlHidden
  class_ViewBiLineItems_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlHidden
  class_ViewBiLineItems_php -- ref --> symbol_Ksfraser_HTML_HtmlElementInterface
  class_ViewBiLineItems_php -- ref --> symbol_Ksfraser_HTML_HtmlFragment
  compare_parsers_php -- ref --> symbol_FOUND_n
  compare_parsers_php -- ref --> symbol_IDENTICAL_n
  fix_test_php -- new --> symbol_QuickEntryPartnerTypeView
  fix_test_php -- ref --> symbol_QuickEntryPartnerTypeView
  fix_test_php -- ref --> symbol_Ksfraser_HTML_Composites_HtmlLabelRow
  GetTransaction_php -- require --> class_bi_transactions_php
  GetTransaction_php -- new --> symbol_Exception
  GetTransaction_php -- new --> symbol_Exception
  GetTransaction_php -- new --> symbol_Exception
  GetTransaction_php -- new --> symbol_Exception
  GetTransaction_php -- new --> symbol_Exception
  GetTransaction_php -- new --> symbol_Exception
  GetTransaction_php -- new --> symbol_Exception
  GetTransaction_php -- new --> symbol_Exception
  GetTransaction_php -- new --> symbol_Exception
  GetTransaction_php -- new --> symbol_Exception
  GetTransaction_php -- new --> symbol_Exception
  html_migration_map_php -- new --> symbol_locations
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Category
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Composites
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Composites
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Composites
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Composites
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Composites
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Composites
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Composites
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Text
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Text
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Text
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Text
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Text
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Text
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Text
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Text
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Text
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Text
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Text
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Text
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Text
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Text
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Text
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Text
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Text
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Structure
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Structure
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Structure
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Structure
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Structure
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Structure
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Structure
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Structure
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Headings
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Headings
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Headings
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Headings
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Headings
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Headings
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Headings
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Links
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Links
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Links
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Lists
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Lists
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Lists
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Lists
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Lists
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Lists
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Lists
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Lists
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Lists
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Lists
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Lists
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Lists
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Tables
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Tables
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Tables
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Tables
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Tables
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Tables
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Tables
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Tables
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Tables
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Tables
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Tables
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Tables
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Forms
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Forms
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Forms
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Forms
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Forms
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Forms
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Forms
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Forms
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Forms
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Forms
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Document
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Document
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Document
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Document
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Media
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Media
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Other
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Other
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Other
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Other
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Other
  html_migration_map_php -- ref --> symbol_Ksfraser_HTML_Elements_Other
  import_statements_debug_version_php -- use --> symbol_Ksfraser_FaBankImport_Service_FileUploadService
  import_statements_debug_version_php -- use --> symbol_Ksfraser_FaBankImport_ValueObject_FileInfo
  import_statements_debug_version_php -- require --> includes_qfx_parser_php
  import_statements_debug_version_php -- require --> Views_module_menu_view_php
  import_statements_debug_version_php -- require --> class_bi_statements_php
  import_statements_debug_version_php -- require --> class_bi_transactions_php
  import_statements_debug_version_php -- new --> symbol__Views_ModuleMenuView
  import_statements_debug_version_php -- new --> symbol_bi_statements_model
  import_statements_debug_version_php -- new --> symbol_BiStatements
  import_statements_debug_version_php -- new --> symbol_bi_transactions_model
  import_statements_debug_version_php -- new --> symbol_BiTransactions
  import_statements_debug_version_php -- new --> symbol_service
  import_statements_debug_version_php -- ref --> symbol_Ksfraser_FaBankImport_Service_FileUploadService
  import_statements_debug_version_php -- ref --> symbol_Ksfraser_FaBankImport_ValueObject_FileInfo
  import_statements_debug_version_php -- ref --> symbol_ModuleMenuView
  import_statements_debug_version_php -- ref --> symbol_Views_ModuleMenuView
  import_statements_debug_version_php -- ref --> symbol_Ksfraser_FaBankImport_Views_ImportUploadForm
  import_statements_php -- use --> symbol_Ksfraser_FaBankImport_Service_FileUploadService
  import_statements_php -- use --> symbol_Ksfraser_FaBankImport_ValueObject_FileInfo
  import_statements_php -- require --> includes_qfx_parser_php
  import_statements_php -- require --> Views_module_menu_view_php
  import_statements_php -- require --> class_bi_statements_php
  import_statements_php -- require --> class_bi_transactions_php
  import_statements_php -- new --> symbol__Views_ModuleMenuView
  import_statements_php -- new --> symbol_bi_statements_model
  import_statements_php -- new --> symbol_BiStatements
  import_statements_php -- new --> symbol_bi_transactions_model
  import_statements_php -- new --> symbol_BiTransactions
  import_statements_php -- new --> symbol_service
  import_statements_php -- ref --> symbol_Ksfraser_FaBankImport_Service_FileUploadService
  import_statements_php -- ref --> symbol_Ksfraser_FaBankImport_ValueObject_FileInfo
  import_statements_php -- ref --> symbol_ModuleMenuView
  import_statements_php -- ref --> symbol_Views_ModuleMenuView
  import_statements_php -- ref --> symbol_Ksfraser_FaBankImport_Views_ImportUploadForm
  manage_partners_data_php -- require --> HTML_Table_php
  manage_partners_data_php -- require --> Views_module_menu_view_php
  manage_partners_data_php -- new --> symbol__Views_ModuleMenuView
  manage_partners_data_php -- new --> symbol_HTML_Table
  manage_partners_data_php -- ref --> symbol_ModuleMenuView
  manage_partners_data_php -- ref --> symbol_Views_ModuleMenuView
  manage_uploaded_files_php -- use --> symbol_Ksfraser_FaBankImport_Services_UploadedFileManager
  manage_uploaded_files_php -- require --> views_module_menu_view_php
  manage_uploaded_files_php -- new --> symbol__Views_ModuleMenuView
  manage_uploaded_files_php -- new --> symbol_UploadedFileManager
  manage_uploaded_files_php -- ref --> symbol_Ksfraser_FaBankImport_Services_UploadedFileManager
  manage_uploaded_files_php -- ref --> symbol_Views_ModuleMenuView
  manage_uploaded_files_php -- ref --> symbol_View
  manual_test_paired_transfers_php -- use --> symbol_OfxParser_Parser
  manual_test_paired_transfers_php -- use --> symbol_KsfBankImport_Services_TransferDirectionAnalyzer
  manual_test_paired_transfers_php -- new --> symbol_Parser
  manual_test_paired_transfers_php -- new --> symbol_DateTime
  manual_test_paired_transfers_php -- new --> symbol_DateTime
  manual_test_paired_transfers_php -- new --> symbol_TransferDirectionAnalyzer
  manual_test_paired_transfers_php -- ref --> symbol_Test_n
  manual_test_paired_transfers_php -- ref --> symbol_OfxParser_Parser
  manual_test_paired_transfers_php -- ref --> symbol_KsfBankImport_Services_TransferDirectionAnalyzer
  manual_test_paired_transfers_php -- ref --> symbol_TransferDirectionAnalyzer_n_n
  manual_test_paired_transfers_php -- ref --> symbol_TransferDirectionAnalyzer_n
  manual_test_paired_transfers_php -- ref --> symbol_QFX_n
  manual_test_paired_transfers_php -- ref --> symbol_QFX_n
  manual_test_paired_transfers_php -- ref --> symbol_Transfers_n
  manual_test_paired_transfers_php -- ref --> symbol_Direction_n
  manual_test_paired_transfers_php -- ref --> symbol_Complete_n
  module_config_php -- use --> symbol_Ksfraser_FaBankImport_Config_ConfigService
  module_config_php -- require --> views_module_menu_view_php
  module_config_php -- new --> symbol__Views_ModuleMenuView
  module_config_php -- ref --> symbol_Ksfraser_FaBankImport_Config_ConfigService
  module_config_php -- ref --> symbol_Views_ModuleMenuView
  mt940_parser_php -- new --> symbol_statement
  mt940_parser_php -- new --> symbol_transaction
  process_statements_php -- use --> symbol_Ksfraser_FaBankImport_views_ProcessStatementsView
  process_statements_php -- require --> Views_module_menu_view_php
  process_statements_php -- require --> class_bank_import_controller_php
  process_statements_php -- require --> ___ksf_modules_common_class_fa_bank_transfer_php
  process_statements_php -- require --> src_Ksfraser_FaBankImport_header_table_php
  process_statements_php -- require --> class_bi_transactions_php
  process_statements_php -- require --> class_bi_lineitem_php
  process_statements_php -- new --> symbol__Views_ModuleMenuView
  process_statements_php -- new --> symbol_bank_import_controller
  process_statements_php -- new --> symbol_bi_transactions_model
  process_statements_php -- new --> symbol_allocation
  process_statements_php -- new --> symbol_items_cart
  process_statements_php -- new --> symbol_fa_bank_transfer
  process_statements_php -- new --> symbol_ksf_modules_table_filter_by_date
  process_statements_php -- new --> symbol_bi_transactions_model
  process_statements_php -- new --> symbol_InvalidReturnType
  process_statements_php -- new --> symbol_ProcessStatementsView
  process_statements_php -- new --> symbol_bi_lineitem
  process_statements_php -- ref --> symbol_Ksfraser_FaBankImport_views_ProcessStatementsView
  process_statements_php -- ref --> symbol_ModuleMenuView
  process_statements_php -- ref --> symbol_Views_ModuleMenuView
  process_statements_php -- ref --> symbol_View
  process_statements_php -- ref --> symbol_View
  process_statements_php -- ref --> symbol_View
  process_statements_php -- ref --> symbol_View
  process_statements_php -- ref --> symbol_View
  process_statements_php -- ref --> symbol_View
  process_statements_php -- ref --> symbol_View
  process_statements_php -- ref --> symbol_View
  process_statements_php -- ref --> symbol_ProcessStatementView
  process_statements_php -- ref --> symbol_Ksfraser_FaBankImport_Results_PaginatedTransactionResult
  process_statements_php -- ref --> symbol_ProcessStatementsView
  process_statements_php -- ref --> symbol_ProcessStatementsView
  process_statements_php -- ref --> symbol_ProcessStatementsView
  qfx_parser_php -- require --> includes_inc
  qfx_parser_php -- new --> symbol_statement
  qfx_parser_php -- new --> symbol_CibcQfxParser
  qfx_parser_php -- new --> symbol_PmcQfxParser
  qfx_parser_php -- new --> symbol_ManuQfxParser
  qfx_parser_php -- new --> symbol_Exception
  test_php -- require --> includes_includes_inc
  test_command_dispatcher_fix_php -- require --> class_bi_transactions_php
  test_command_dispatcher_fix_php -- new --> symbol_bi_transactions_model
  test_html_links_manual_php -- use --> symbol_Ksfraser_HTML_Elements__HtmlEmail__HtmlA__HtmlString_
  test_html_links_manual_php -- use --> symbol_Ksfraser_HTML_Elements_HtmlRaw
  test_html_links_manual_php -- new --> symbol_HtmlEmail
  test_html_links_manual_php -- new --> symbol_HtmlString
  test_html_links_manual_php -- new --> symbol_HtmlEmail
  test_html_links_manual_php -- new --> symbol_HtmlEmail
  test_html_links_manual_php -- new --> symbol_HtmlEmail
  test_html_links_manual_php -- new --> symbol_HtmlEmail
  test_html_links_manual_php -- new --> symbol_HtmlA
  test_html_links_manual_php -- new --> symbol_HtmlString
  test_html_links_manual_php -- new --> symbol_HtmlA
  test_html_links_manual_php -- new --> symbol_HtmlA
  test_html_links_manual_php -- new --> symbol_HtmlA
  test_html_links_manual_php -- new --> symbol_HtmlRaw
  test_html_links_manual_php -- new --> symbol_HtmlA
  test_html_links_manual_php -- new --> symbol_HtmlEmail
  test_html_links_manual_php -- new --> symbol_HtmlEmail
  test_html_links_manual_php -- new --> symbol_HtmlA
  test_html_links_manual_php -- ref --> symbol_Ksfraser_HTML_Elements
  test_html_links_manual_php -- ref --> symbol_Ksfraser_HTML_Elements_HtmlRaw
  test_ksf_fork_php -- new --> symbol_qfx_parser
  test_nested_links_php -- use --> symbol_Ksfraser_HTML_Elements__HtmlA__HtmlEmail__HtmlString_
  test_nested_links_php -- new --> symbol_HtmlA
  test_nested_links_php -- new --> symbol_HtmlA
  test_nested_links_php -- new --> symbol_HtmlString
  test_nested_links_php -- new --> symbol_HtmlA
  test_nested_links_php -- new --> symbol_HtmlA
  test_nested_links_php -- new --> symbol_HtmlA
  test_nested_links_php -- new --> symbol_HtmlEmail
  test_nested_links_php -- new --> symbol_HtmlA
  test_nested_links_php -- new --> symbol_HtmlA
  test_nested_links_php -- new --> symbol_HtmlEmail
  test_nested_links_php -- ref --> symbol_Ksfraser_HTML_Elements
  test_production_parser_php -- new --> symbol__OfxParser_Parser
  test_production_parser_php -- ref --> symbol_OfxParser_Parser
  test_raw_parser_php -- new --> symbol__OfxParser_Parser
  test_raw_parser_php -- ref --> symbol_OfxParser_Parser
  test_raw_parser_php -- ref --> symbol_OfxParser_Parser
  test_wrapper_php -- use --> symbol_Ksfraser_HTML_Composites_HTML_ROW_LABEL
  test_wrapper_php -- use --> symbol_Ksfraser_HTML_Composites_HTML_ROW
  test_wrapper_php -- require --> vendor_autoload_php
  test_wrapper_php -- new --> symbol_HTML_ROW_LABEL
  test_wrapper_php -- new --> symbol_HTML_ROW_LABEL
  test_wrapper_php -- new --> symbol_HTML_ROW_LABEL
  test_wrapper_php -- new --> symbol_HTML_ROW
  test_wrapper_php -- ref --> symbol_Ksfraser_HTML_Composites_HTML_ROW_LABEL
  test_wrapper_php -- ref --> symbol_Ksfraser_HTML_Composites_HTML_ROW
  update_process_statements_php -- new --> symbol__Ksfraser_FaBankImport_Views_ProcessStatementsView
  update_process_statements_php -- new --> symbol__Ksfraser_FaBankImport_Views_ProcessStatementsView
  update_process_statements_php -- ref --> symbol_ProcessStatementsView
  update_process_statements_php -- ref --> symbol_ProcessStatementsView
  update_process_statements_php -- ref --> symbol_Ksfraser_FaBankImport_Views_ProcessStatementsView
  update_process_statements_php -- ref --> symbol_Ksfraser_FaBankImport_Views_ProcessStatementsView
  validate_gl_entries_php -- use --> symbol_Ksfraser_FaBankImport_Services_TransactionGLValidator
  validate_gl_entries_php -- require --> views_module_menu_view_php
  validate_gl_entries_php -- new --> symbol__Views_ModuleMenuView
  validate_gl_entries_php -- new --> symbol_TransactionGLValidator
  validate_gl_entries_php -- ref --> symbol_Ksfraser_FaBankImport_Services_TransactionGLValidator
  validate_gl_entries_php -- ref --> symbol_Views_ModuleMenuView
  VendorListManager_php -- new --> symbol_self
  VendorListManager_php -- new --> symbol__InvalidArgumentException
  view_statements_php -- require --> Views_module_menu_view_php
  view_statements_php -- new --> symbol__Views_ModuleMenuView
  view_statements_php -- ref --> symbol_View
  view_statements_php -- ref --> symbol_ModuleMenuView
  view_statements_php -- ref --> symbol_Views_ModuleMenuView
  cron_monitor_performance_php -- use --> symbol_Ksfraser_Application_Services_AlertService
  cron_monitor_performance_php -- use --> symbol_Ksfraser_Application_Services_MetricsAggregator
  cron_monitor_performance_php -- use --> symbol_Ksfraser_Application_Config_Config
  cron_monitor_performance_php -- new --> symbol_ErrorException
  cron_monitor_performance_php -- ref --> symbol_Ksfraser_Application_Services_AlertService
  cron_monitor_performance_php -- ref --> symbol_Ksfraser_Application_Services_MetricsAggregator
  cron_monitor_performance_php -- ref --> symbol_Ksfraser_Application_Config_Config
  docs_REFACTORING_EXAMPLES_php -- use --> symbol_Ksfraser_FaBankImport_Commands_CommandDispatcher
  docs_REFACTORING_EXAMPLES_php -- use --> symbol_Ksfraser_FaBankImport_Results_TransactionResult
  docs_REFACTORING_EXAMPLES_php -- new --> symbol_CommandDispatcher
  docs_REFACTORING_EXAMPLES_php -- new --> symbol_CommandDispatcher
  docs_REFACTORING_EXAMPLES_php -- new --> symbol_CommandDispatcher
  docs_REFACTORING_EXAMPLES_php -- new --> symbol_implementations
  docs_REFACTORING_EXAMPLES_php -- new --> symbol_CommandDispatcher
  docs_REFACTORING_EXAMPLES_php -- new --> symbol_class
  docs_REFACTORING_EXAMPLES_php -- new --> symbol_ReflectionClass
  docs_REFACTORING_EXAMPLES_php -- new --> symbol_CommandDispatcher
  docs_REFACTORING_EXAMPLES_php -- ref --> symbol_Ksfraser_FaBankImport
  docs_REFACTORING_EXAMPLES_php -- ref --> symbol_Ksfraser_FaBankImport_Commands_CommandDispatcher
  docs_REFACTORING_EXAMPLES_php -- ref --> symbol_Ksfraser_FaBankImport_Results_TransactionResult
  duplicates_backup_20251116_183246_class_bank_import_controller_php -- require --> ksf_modules_common_class_origin_php
  duplicates_backup_20251116_183246_class_bank_import_controller_php -- require --> duplicates_backup_20251116_183246_class_bi_transaction_php
  duplicates_backup_20251116_183246_class_bank_import_controller_php -- require --> duplicates_backup_20251116_183246_class_bi_transactions_php
  duplicates_backup_20251116_183246_class_bank_import_controller_php -- require --> duplicates_backup_20251116_183246_includes_pdata_inc
  duplicates_backup_20251116_183246_class_bank_import_controller_php -- require --> ksf_modules_common_class_fa_bank_transfer_php
  duplicates_backup_20251116_183246_class_bank_import_controller_php -- new --> symbol_bi_transaction
  duplicates_backup_20251116_183246_class_bank_import_controller_php -- new --> symbol_bi_transactions_model
  duplicates_backup_20251116_183246_class_bank_import_controller_php -- new --> symbol_bi_transaction
  duplicates_backup_20251116_183246_class_bank_import_controller_php -- new --> symbol_bi_transactions_model
  duplicates_backup_20251116_183246_class_bank_import_controller_php -- new --> symbol_bi_transactions_model
  duplicates_backup_20251116_183246_class_bank_import_controller_php -- new --> symbol_customer
  duplicates_backup_20251116_183246_class_bank_import_controller_php -- new --> symbol_vendor
  duplicates_backup_20251116_183246_class_bank_import_controller_php -- new --> symbol_bi_transactions_model
  duplicates_backup_20251116_183246_class_bank_import_controller_php -- new --> symbol_items_cart
  duplicates_backup_20251116_183246_class_bank_import_controller_php -- new --> symbol_Exception
  duplicates_backup_20251116_183246_class_bank_import_controller_php -- new --> symbol_Exception
  duplicates_backup_20251116_183246_class_bank_import_controller_php -- new --> symbol_Exception
  duplicates_backup_20251116_183246_class_bank_import_controller_php -- new --> symbol_Exception
  duplicates_backup_20251116_183246_class_bank_import_controller_php -- new --> symbol_Exception
  duplicates_backup_20251116_183246_class_bank_import_controller_php -- new --> symbol_Reference
  duplicates_backup_20251116_183246_class_bank_import_controller_php -- new --> symbol_Exception
  duplicates_backup_20251116_183246_class_bank_import_controller_php -- new --> symbol_Reference
  duplicates_backup_20251116_183246_class_bank_import_controller_php -- new --> symbol_items_cart
  duplicates_backup_20251116_183246_class_bank_import_controller_php -- new --> symbol_fa_customer_payment
  duplicates_backup_20251116_183246_class_bank_import_controller_php -- new --> symbol_fa_bank_transfer
  duplicates_backup_20251116_183246_class_bank_import_controller_php -- ref --> symbol_View
  duplicates_backup_20251116_183246_class_bank_import_controller_php -- ref --> symbol_View
  duplicates_backup_20251116_183246_class_bank_import_controller_php -- ref --> symbol_View
  duplicates_backup_20251116_183246_class_bank_import_controller_php -- ref --> symbol_View
  duplicates_backup_20251116_183246_class_bank_import_controller_php -- ref --> symbol_View
  duplicates_backup_20251116_183246_class_bank_import_controller_php -- ref --> symbol_View
  duplicates_backup_20251116_183246_class_bank_import_controller_php -- ref --> symbol_View
  duplicates_backup_20251116_183246_class_bi_counterparty_model_php -- use --> symbol_Ksfraser_common_GenericFaInterface
  duplicates_backup_20251116_183246_class_bi_counterparty_model_php -- use --> symbol_Ksfraser_common_Defines
  duplicates_backup_20251116_183246_class_bi_counterparty_model_php -- require --> ksf_modules_commone_class_generic_fa_interface_php
  duplicates_backup_20251116_183246_class_bi_counterparty_model_php -- require --> ksf_modules_commone_defines_inc_php
  duplicates_backup_20251116_183246_class_bi_counterparty_model_php -- ref --> symbol_Ksfraser_common_GenericFaInterface
  duplicates_backup_20251116_183246_class_bi_counterparty_model_php -- ref --> symbol_Ksfraser_common_Defines
  duplicates_backup_20251116_183246_class_bi_counterparty_model_php -- ref --> symbol_GenericFaInterfaceModel
  duplicates_backup_20251116_183246_class_bi_lineitem_php -- use --> symbol_Ksfraser_common_GenericFaInterface
  duplicates_backup_20251116_183246_class_bi_lineitem_php -- use --> symbol_Ksfraser_common_Defines
  duplicates_backup_20251116_183246_class_bi_lineitem_php -- use --> symbol_Ksfraser_frontaccounting_FaBankAccounts
  duplicates_backup_20251116_183246_class_bi_lineitem_php -- use --> symbol_Ksfraser_frontaccounting_FaGl
  duplicates_backup_20251116_183246_class_bi_lineitem_php -- use --> symbol_Ksfraser_frontaccounting_FaCustomerPayment
  duplicates_backup_20251116_183246_class_bi_lineitem_php -- require --> ksf_modules_common_class_fa_bank_accounts_php
  duplicates_backup_20251116_183246_class_bi_lineitem_php -- require --> duplicates_backup_20251116_183246_class_bi_transactions_php
  duplicates_backup_20251116_183246_class_bi_lineitem_php -- new --> symbol_FaBankAccounts
  duplicates_backup_20251116_183246_class_bi_lineitem_php -- new --> symbol_bi_transactions_model
  duplicates_backup_20251116_183246_class_bi_lineitem_php -- new --> symbol_FaGl
  duplicates_backup_20251116_183246_class_bi_lineitem_php -- new --> symbol__KSFRASER_FA_fa_gl
  duplicates_backup_20251116_183246_class_bi_lineitem_php -- new --> symbol_fa_customer_payment
  duplicates_backup_20251116_183246_class_bi_lineitem_php -- new --> symbol_transaction
  duplicates_backup_20251116_183246_class_bi_lineitem_php -- ref --> symbol_Ksfraser_common_GenericFaInterface
  duplicates_backup_20251116_183246_class_bi_lineitem_php -- ref --> symbol_Ksfraser_common_Defines
  duplicates_backup_20251116_183246_class_bi_lineitem_php -- ref --> symbol_Ksfraser_frontaccounting_FaBankAccounts
  duplicates_backup_20251116_183246_class_bi_lineitem_php -- ref --> symbol_Ksfraser_frontaccounting_FaGl
  duplicates_backup_20251116_183246_class_bi_lineitem_php -- ref --> symbol_KSFRASER_FA_fa_gl
  duplicates_backup_20251116_183246_class_bi_lineitem_php -- ref --> symbol_Ksfraser_frontaccounting_FaCustomerPayment
  duplicates_backup_20251116_183246_class_bi_partners_data_php -- ref --> symbol_SHOPPERS_nSHOPPERS_n
  duplicates_backup_20251116_183246_class_bi_statements_php -- use --> symbol_Ksfraser_common_GenericFaInterface
  duplicates_backup_20251116_183246_class_bi_statements_php -- use --> symbol_Ksfraser_common_Defines
  duplicates_backup_20251116_183246_class_bi_statements_php -- require --> ksf_modules_common_class_generic_fa_interface_php
  duplicates_backup_20251116_183246_class_bi_statements_php -- require --> ksf_modules_common_defines_inc_php
  duplicates_backup_20251116_183246_class_bi_statements_php -- new --> symbol_Exception
  duplicates_backup_20251116_183246_class_bi_statements_php -- new --> symbol_Exception
  duplicates_backup_20251116_183246_class_bi_statements_php -- new --> symbol_Exception
  duplicates_backup_20251116_183246_class_bi_statements_php -- ref --> symbol_Ksfraser_common_GenericFaInterface
  duplicates_backup_20251116_183246_class_bi_statements_php -- ref --> symbol_Ksfraser_common_Defines
  duplicates_backup_20251116_183246_class_bi_transactions_php -- use --> symbol_Ksfraser_common_GenericFaInterface
  duplicates_backup_20251116_183246_class_bi_transactions_php -- use --> symbol_Ksfraser_common_Defines
  duplicates_backup_20251116_183246_class_bi_transactions_php -- new --> symbol_Exception
  duplicates_backup_20251116_183246_class_bi_transactions_php -- new --> symbol_Exception
  duplicates_backup_20251116_183246_class_bi_transactions_php -- new --> symbol_Exception
  duplicates_backup_20251116_183246_class_bi_transactions_php -- new --> symbol_Exception
  duplicates_backup_20251116_183246_class_bi_transactions_php -- new --> symbol_Exception
  duplicates_backup_20251116_183246_class_bi_transactions_php -- new --> symbol_Exception
  duplicates_backup_20251116_183246_class_bi_transactions_php -- new --> symbol_Exception
  duplicates_backup_20251116_183246_class_bi_transactions_php -- new --> symbol_Exception
  duplicates_backup_20251116_183246_class_bi_transactions_php -- new --> symbol_Exception
  duplicates_backup_20251116_183246_class_bi_transactions_php -- new --> symbol_Exception
  duplicates_backup_20251116_183246_class_bi_transactions_php -- new --> symbol_Exception
  duplicates_backup_20251116_183246_class_bi_transactions_php -- new --> symbol_Exception
  duplicates_backup_20251116_183246_class_bi_transactions_php -- new --> symbol_Exception
  duplicates_backup_20251116_183246_class_bi_transactions_php -- new --> symbol_Exception
  duplicates_backup_20251116_183246_class_bi_transactions_php -- new --> symbol_Exception
  duplicates_backup_20251116_183246_class_bi_transactions_php -- new --> symbol_Exception
  duplicates_backup_20251116_183246_class_bi_transactions_php -- new --> symbol_Exception
  duplicates_backup_20251116_183246_class_bi_transactions_php -- ref --> symbol_Ksfraser_common_GenericFaInterface
  duplicates_backup_20251116_183246_class_bi_transactions_php -- ref --> symbol_Ksfraser_common_Defines
  duplicates_backup_20251116_183246_class_bi_transactionTitle_model_php -- use --> symbol_Ksfraser_common_GenericFaInterface
  duplicates_backup_20251116_183246_class_bi_transactionTitle_model_php -- use --> symbol_Ksfraser_common_Defines
  duplicates_backup_20251116_183246_class_bi_transactionTitle_model_php -- require --> ksf_modules_commone_class_generic_fa_interface_php
  duplicates_backup_20251116_183246_class_bi_transactionTitle_model_php -- require --> ksf_modules_commone_defines_inc_php
  duplicates_backup_20251116_183246_class_bi_transactionTitle_model_php -- ref --> symbol_Ksfraser_common_GenericFaInterface
  duplicates_backup_20251116_183246_class_bi_transactionTitle_model_php -- ref --> symbol_Ksfraser_common_Defines
  duplicates_backup_20251116_183246_class_transactions_table_php -- new --> symbol_transaction_table_row
  duplicates_backup_20251116_183246_class_transactions_table_php -- new --> symbol_transaction
  duplicates_backup_20251116_183246_class_ViewBiLineItems_php -- new --> symbol_HTML_TABLE
  duplicates_backup_20251116_183246_class_ViewBiLineItems_php -- new --> symbol_TransDate
  duplicates_backup_20251116_183246_class_ViewBiLineItems_php -- new --> symbol_TransType
  duplicates_backup_20251116_183246_class_ViewBiLineItems_php -- new --> symbol_OurBankAccount
  duplicates_backup_20251116_183246_class_ViewBiLineItems_php -- new --> symbol_OtherBankAccount
  duplicates_backup_20251116_183246_class_ViewBiLineItems_php -- new --> symbol_AmountCharges
  duplicates_backup_20251116_183246_class_ViewBiLineItems_php -- new --> symbol_TransTitle
  duplicates_backup_20251116_183246_class_ViewBiLineItems_php -- new --> symbol_AddCustomerButton
  duplicates_backup_20251116_183246_class_ViewBiLineItems_php -- new --> symbol_AddVendorButton
  duplicates_backup_20251116_183246_class_ViewBiLineItems_php -- new --> symbol_HtmlString
  duplicates_backup_20251116_183246_class_ViewBiLineItems_php -- new --> symbol_HtmlAttribute
  duplicates_backup_20251116_183246_class_ViewBiLineItems_php -- new --> symbol_HtmlAttribute
  duplicates_backup_20251116_183246_class_ViewBiLineItems_php -- new --> symbol_CustomerTransactionDetails
  duplicates_backup_20251116_183246_class_ViewBiLineItems_php -- new --> symbol_fa_customer_payment
  duplicates_backup_20251116_183246_class_ViewBiLineItems_php -- new --> symbol_transaction
  duplicates_backup_20251116_183246_import_statements_php -- require --> duplicates_backup_20251116_183246_includes_qfx_parser_php
  duplicates_backup_20251116_183246_import_statements_php -- require --> duplicates_backup_20251116_183246_Views_module_menu_view_php
  duplicates_backup_20251116_183246_import_statements_php -- require --> duplicates_backup_20251116_183246_class_bi_statements_php
  duplicates_backup_20251116_183246_import_statements_php -- require --> duplicates_backup_20251116_183246_class_bi_transactions_php
  duplicates_backup_20251116_183246_import_statements_php -- new --> symbol__Views_ModuleMenuView
  duplicates_backup_20251116_183246_import_statements_php -- new --> symbol_bi_statements_model
  duplicates_backup_20251116_183246_import_statements_php -- new --> symbol_BiStatements
  duplicates_backup_20251116_183246_import_statements_php -- new --> symbol_bi_transactions_model
  duplicates_backup_20251116_183246_import_statements_php -- new --> symbol_BiTransactions
  duplicates_backup_20251116_183246_import_statements_php -- ref --> symbol_ModuleMenuView
  duplicates_backup_20251116_183246_import_statements_php -- ref --> symbol_Views_ModuleMenuView
  duplicates_backup_20251116_183246_process_statements_copilot_refactored_php -- require --> duplicates_backup_20251116_183246_class_bank_import_controller_php
  duplicates_backup_20251116_183246_process_statements_copilot_refactored_php -- new --> symbol_bank_import_controller
  duplicates_backup_20251116_183246_process_statements_preclean_php -- require --> ksf_modules_common_class_fa_bank_transfer_php
  duplicates_backup_20251116_183246_process_statements_preclean_php -- require --> duplicates_backup_20251116_183246_header_table_php
  duplicates_backup_20251116_183246_process_statements_preclean_php -- require --> duplicates_backup_20251116_183246_class_bi_transactions_php
  duplicates_backup_20251116_183246_process_statements_preclean_php -- require --> duplicates_backup_20251116_183246_class_bi_lineitem_php
  duplicates_backup_20251116_183246_process_statements_preclean_php -- new --> symbol_items_cart
  duplicates_backup_20251116_183246_process_statements_preclean_php -- new --> symbol_fa_customer_payment
  duplicates_backup_20251116_183246_process_statements_preclean_php -- new --> symbol_items_cart
  duplicates_backup_20251116_183246_process_statements_preclean_php -- new --> symbol_fa_bank_transfer
  duplicates_backup_20251116_183246_process_statements_preclean_php -- new --> symbol_ksf_modules_table_filter_by_date
  duplicates_backup_20251116_183246_process_statements_preclean_php -- new --> symbol_bi_transactions_model
  duplicates_backup_20251116_183246_process_statements_preclean_php -- new --> symbol_bi_lineitem
  duplicates_backup_20251116_183246_process_statements_preclean_php -- new --> symbol_transaction
  duplicates_backup_20251116_183246_process_statements_preclean_php -- new --> symbol_fa_customer_payment
  duplicates_backup_20251116_183246_process_statements_preclean_php -- ref --> symbol_View
  duplicates_backup_20251116_183246_process_statements_preclean_php -- ref --> symbol_View
  duplicates_backup_20251116_183246_process_statements_preclean_php -- ref --> symbol_View
  duplicates_backup_20251116_183246_process_statements_preclean_php -- ref --> symbol_View
  duplicates_backup_20251116_183246_process_statements_preclean_php -- ref --> symbol_View
  duplicates_backup_20251116_183246_process_statements_preclean_php -- ref --> symbol_View
  duplicates_backup_20251116_183246_process_statements_preclean_php -- ref --> symbol_View
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- require --> ksf_modules_common_class_fa_bank_accounts_php
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- require --> duplicates_backup_20251116_183246_class_bi_transactions_php
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- new --> symbol_Exception
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- new --> symbol_HTML_ROW
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- new --> symbol_Exception
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- new --> symbol__RuntimeException
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- new --> symbol__Exception
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- new --> symbol__Exception
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- new --> symbol_HTML_TABLE
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- new --> symbol_TransDate
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- new --> symbol_TransType
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- new --> symbol_OurBankAccount
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- new --> symbol_OtherBankAccount
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- new --> symbol_AmountCharges
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- new --> symbol_TransTitle
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- new --> symbol_AddCustomerButton
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- new --> symbol_AddVendorButton
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- new --> symbol_fa_customer_payment
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- new --> symbol_transaction
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- new --> symbol_TransactionTypeLabel
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- new --> symbol_fa_bank_accounts
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- new --> symbol_FaBankAccounts
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- new --> symbol_AddVendorButton
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- new --> symbol_AddCustomerButton
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- new --> symbol_Exception
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- new --> symbol_Exception
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- new --> symbol_Exception
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- new --> symbol_bi_transactions_model
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- new --> symbol_FaGl
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- new --> symbol__KSFRASER_FA_fa_gl
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- new --> symbol_fa_gl
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- new --> symbol_fa_customer_payment
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- new --> symbol_transaction
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- ref --> symbol_Ksfraser_common_GenericFaInterface
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- ref --> symbol_Ksfraser_common_Defines
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- ref --> symbol_Ksfraser_HTML_HtmlElementInterface
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- ref --> symbol_HTML_HTML_ROW
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- ref --> symbol_View
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- ref --> symbol_Ksfraser_frontaccounting_FaBankAccounts
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- ref --> symbol_Ksfraser_frontaccounting_FaGl
  duplicates_backup_20251116_183246_views_class_bi_lineitem_php -- ref --> symbol_KSFRASER_FA_fa_gl
  duplicates_backup_20251116_183246_view_statements_php -- require --> duplicates_backup_20251116_183246_Views_module_menu_view_php
  duplicates_backup_20251116_183246_view_statements_php -- new --> symbol__Views_ModuleMenuView
  duplicates_backup_20251116_183246_view_statements_php -- ref --> symbol_View
  duplicates_backup_20251116_183246_view_statements_php -- ref --> symbol_ModuleMenuView
  duplicates_backup_20251116_183246_view_statements_php -- ref --> symbol_Views_ModuleMenuView
  includes_example_ofx_php -- require --> includes_vendor_autoload_php
  includes_example_ofx_php -- require --> includes_lib_OfxParser_Parser_php
  includes_example_ofx_php -- new --> symbol_OfxParser_Parser
  includes_example_ofx_php -- new --> symbol_Parser
  includes_example_ofx_php -- ref --> symbol_OfxParser_Parser
  includes_example_ofx_php -- ref --> symbol_OfxParser_Parser
  includes_example_ofx_php -- ref --> symbol_OfxParser_Parser
  includes_mt940_parser_php -- new --> symbol_statement
  includes_mt940_parser_php -- new --> symbol_transaction
  includes_parser_php -- new --> symbol__InvalidArgumentException
  includes_parser_php -- new --> symbol_Ofx
  includes_parser_php -- new --> symbol__RuntimeException
  includes_Parser00_php -- new --> symbol__InvalidArgumentException
  includes_Parser00_php -- new --> symbol_Ofx
  includes_Parser00_php -- new --> symbol__RuntimeException
  includes_Parser23_php -- new --> symbol__InvalidArgumentException
  includes_Parser23_php -- new --> symbol_Ofx
  includes_Parser23_php -- new --> symbol__RuntimeException
  includes_qfx_parser_php -- require --> includes_includes_inc
  includes_qfx_parser_php -- new --> symbol_statement
  includes_qfx_parser_php -- new --> symbol_OfxParser_Parser
  includes_qfx_parser_php -- new --> symbol_statement
  includes_qfx_parser_php -- new --> symbol_statement
  includes_qfx_parser_php -- new --> symbol_transaction
  includes_qfx_parser_php -- new --> symbol_transaction
  includes_qfx_parser_php -- new --> symbol_transaction
  includes_qfx_parser_php -- ref --> symbol_OfxParser_Parser
  includes_qfx_parser_php -- ref --> symbol_SET_n
  includes_ro_bcr_csv_parser_php -- new --> symbol_statement
  includes_ro_bcr_csv_parser_php -- new --> symbol_statement
  includes_ro_bcr_csv_parser_php -- new --> symbol_statement
  includes_ro_bcr_csv_parser_php -- new --> symbol_transaction
  includes_ro_ing_csv_parser_php -- new --> symbol_statement
  includes_ro_ing_csv_parser_php -- new --> symbol_statement
  includes_ro_ing_csv_parser_php -- new --> symbol_statement
  includes_ro_ing_csv_parser_php -- new --> symbol_transaction
  includes_ro_ing_csv_parser_php -- new --> symbol_transaction
  includes_ro_ing_csv_parser_php -- new --> symbol_transaction
  includes_ro_ing_csv_parser_php -- new --> symbol_transaction
  includes_ro_wmmc_csv_parser_php -- require --> includes_include_inc
  includes_ro_wmmc_csv_parser_php -- new --> symbol_statement
  includes_ro_wmmc_csv_parser_php -- new --> symbol_statement
  includes_ro_wmmc_csv_parser_php -- new --> symbol_statement
  includes_ro_wmmc_csv_parser_php -- new --> symbol_transaction
  includes_ro_wmmc_csv_parser_php -- new --> symbol_transaction
  includes_ro_wmmc_csv_parser_php -- new --> symbol_transaction
  includes_ro_wmmc_csv_parser_php -- new --> symbol_transaction
  includes_test_import_php -- require --> includes_banking_php
  includes_test_import_php -- require --> includes_parser_php
  includes_test_import_php -- require --> includes_mt940_parser_php
  includes_test_import_php -- require --> includes_qfx_parser_php
  includes_test_import_php -- require --> class_bi_statements_php
  includes_test_import_php -- require --> class_bi_transactions_php
  includes_test_import_php -- new --> symbol_qfx_parser
  includes_test_import_php -- new --> symbol_bi_statements_model
  includes_test_import_php -- new --> symbol_bi_transactions_model
  includes_test_import_php -- new --> symbol_transaction_n
  includes_test_import_php -- ref --> symbol_Inserting_n
  includes_test_import_php -- ref --> symbol_Updating_n
  includes_test_parser_php -- require --> includes_banking_php
  includes_test_parser_php -- require --> includes_parser_php
  includes_test_parser_php -- require --> includes_mt940_parser_php
  includes_test_parser_php -- require --> includes_qfx_parser_php
  includes_test_parser_php -- require --> includes_ro_wmmc_csv_parser_php
  includes_test_parser_php -- require --> includes_ro_ing_csv_parser_php
  includes_test_parser_php -- require --> includes_ro_bcr_csv_parser_php
  includes_test_parser_php -- require --> includes_ro_brd_mt940_parser_php
  includes_test_parser_php -- new --> symbol_qfx_parser
  includes_test_parser_php -- new --> symbol_ro_wmmc_csv_parser
  includes_test_parser_php -- new --> symbol_ro_ing_csv_parser
  includes_test_parser_php -- new --> symbol_ro_bcr_csv_parser
  includes_test_parser_php -- new --> symbol_ro_brd_mt940_parser
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Ofx_php -- use --> symbol_SimpleXMLElement
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Ofx_php -- use --> symbol_OfxParser_Entities_AccountInfo
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Ofx_php -- use --> symbol_OfxParser_Entities_BankAccount
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Ofx_php -- use --> symbol_OfxParser_Entities_Institute
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Ofx_php -- use --> symbol_OfxParser_Entities_SignOn
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Ofx_php -- use --> symbol_OfxParser_Entities_Statement
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Ofx_php -- use --> symbol_OfxParser_Entities_Status
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Ofx_php -- use --> symbol_OfxParser_Entities_Transaction
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Ofx_php -- new --> symbol_SignOn
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Ofx_php -- new --> symbol_Institute
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Ofx_php -- new --> symbol_AccountInfo
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Ofx_php -- new --> symbol_BankAccount
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Ofx_php -- new --> symbol_Statement
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Ofx_php -- new --> symbol_BankAccount
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Ofx_php -- new --> symbol_Statement
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Ofx_php -- new --> symbol_Transaction
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Ofx_php -- new --> symbol_Status
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Ofx_php -- new --> symbol__DateTime
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Ofx_php -- new --> symbol__RuntimeException
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Ofx_php -- ref --> symbol_OfxParser_Entities_AccountInfo
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Ofx_php -- ref --> symbol_OfxParser_Entities_BankAccount
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Ofx_php -- ref --> symbol_OfxParser_Entities_Institute
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Ofx_php -- ref --> symbol_OfxParser_Entities_SignOn
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Ofx_php -- ref --> symbol_OfxParser_Entities_Statement
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Ofx_php -- ref --> symbol_OfxParser_Entities_Status
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Ofx_php -- ref --> symbol_OfxParser_Entities_Transaction
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Parser_php -- new --> symbol_Ofx
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Parser_php -- new --> symbol__InvalidArgumentException
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Parser_php -- new --> symbol__InvalidArgumentException
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Parser_php -- new --> symbol_Ofx
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Parser_php -- new --> symbol__RuntimeException
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Parser_php -- new --> symbol_line
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Parser_php -- new --> symbol_lines
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Parser_php -- ref --> symbol_DATA_n
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Parser_orig_mod_php -- new --> symbol__InvalidArgumentException
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Parser_orig_mod_php -- new --> symbol_Ofx
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Parser_orig_mod_php -- new --> symbol__RuntimeException
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Parser_rep_php -- use --> symbol_SimpleXMLElement
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Parser_rep_php -- new --> symbol_Ofx
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Parser_rep_php -- new --> symbol__InvalidArgumentException
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Parser_rep_php -- new --> symbol__RuntimeException
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Parser_rep_php -- new --> symbol_lines
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Entities_AbstractEntity_php -- ref --> symbol_OfxParser_Entities
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Entities_AccountInfo_php -- ref --> symbol_OfxParser_Entities
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Entities_BankAccount_php -- ref --> symbol_OfxParser_Entities
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Entities_BankAccountInformation_php -- ref --> symbol_OfxParser_Entities
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Entities_BankingAccount_php -- ref --> symbol_OfxParser_Entities
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Entities_CreditCardAccount_php -- ref --> symbol_OfxParser_Entities
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Entities_CreditCardAccountInfo_php -- ref --> symbol_OfxParser_Entities
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Entities_Institute_php -- ref --> symbol_OfxParser_Entities
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Entities_SignOn_php -- ref --> symbol_OfxParser_Entities
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Entities_Statement_php -- ref --> symbol_OfxParser_Entities
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Entities_Status_php -- ref --> symbol_OfxParser_Entities
  includes_vendor_asgrim_ofxparser_lib_OfxParser_Entities_Transaction_php -- ref --> symbol_OfxParser_Entities
  includes_vendor_asgrim_ofxparser_tests_OfxParser_OfxTest_php -- use --> symbol_OfxParser_Ofx
  includes_vendor_asgrim_ofxparser_tests_OfxParser_OfxTest_php -- new --> symbol__ReflectionMethod
  includes_vendor_asgrim_ofxparser_tests_OfxParser_OfxTest_php -- new --> symbol_Ofx
  includes_vendor_asgrim_ofxparser_tests_OfxParser_OfxTest_php -- new --> symbol__DateTime
  includes_vendor_asgrim_ofxparser_tests_OfxParser_OfxTest_php -- new --> symbol__ReflectionMethod
  includes_vendor_asgrim_ofxparser_tests_OfxParser_OfxTest_php -- new --> symbol_Ofx
  includes_vendor_asgrim_ofxparser_tests_OfxParser_OfxTest_php -- new --> symbol_Ofx
  includes_vendor_asgrim_ofxparser_tests_OfxParser_OfxTest_php -- new --> symbol_Ofx
  includes_vendor_asgrim_ofxparser_tests_OfxParser_OfxTest_php -- new --> symbol_Ofx
  includes_vendor_asgrim_ofxparser_tests_OfxParser_OfxTest_php -- ref --> symbol_OfxParser_Ofx
  includes_vendor_asgrim_ofxparser_tests_OfxParser_OfxTest_php -- ref --> symbol_OfxParser_Ofx
  includes_vendor_asgrim_ofxparser_tests_OfxParser_ParserTest_php -- use --> symbol_OfxParser_Parser
  includes_vendor_asgrim_ofxparser_tests_OfxParser_ParserTest_php -- new --> symbol_Parser
  includes_vendor_asgrim_ofxparser_tests_OfxParser_ParserTest_php -- new --> symbol__ReflectionMethod
  includes_vendor_asgrim_ofxparser_tests_OfxParser_ParserTest_php -- new --> symbol_Parser
  includes_vendor_asgrim_ofxparser_tests_OfxParser_ParserTest_php -- new --> symbol__ReflectionMethod
  includes_vendor_asgrim_ofxparser_tests_OfxParser_ParserTest_php -- new --> symbol_Parser
  includes_vendor_asgrim_ofxparser_tests_OfxParser_ParserTest_php -- new --> symbol__ReflectionMethod
  includes_vendor_asgrim_ofxparser_tests_OfxParser_ParserTest_php -- new --> symbol_Parser
  includes_vendor_asgrim_ofxparser_tests_OfxParser_ParserTest_php -- new --> symbol__ReflectionMethod
  includes_vendor_asgrim_ofxparser_tests_OfxParser_ParserTest_php -- new --> symbol_Parser
  includes_vendor_asgrim_ofxparser_tests_OfxParser_ParserTest_php -- new --> symbol_Parser
  includes_vendor_asgrim_ofxparser_tests_OfxParser_ParserTest_php -- new --> symbol_Parser
  includes_vendor_asgrim_ofxparser_tests_OfxParser_ParserTest_php -- ref --> symbol_OfxParser_Parser
  includes_vendor_asgrim_ofxparser_tests_OfxParser_ParserTest_php -- ref --> symbol_OfxParser_Parser
  includes_vendor_composer_autoload_classmap_php -- ref --> symbol_Composer__InstalledVersions
  includes_vendor_composer_autoload_real_php -- new --> symbol__Composer_Autoload_ClassLoader
  includes_vendor_composer_autoload_real_php -- ref --> symbol_Composer_Autoload_ClassLoader
  includes_vendor_composer_autoload_real_php -- ref --> symbol_Composer_Autoload_ClassLoader
  includes_vendor_composer_autoload_real_php -- ref --> symbol_Composer_Autoload_ClassLoader
  includes_vendor_composer_autoload_real_php -- ref --> symbol_Composer_Autoload_ComposerStaticInited17e532aa9e766e4256c6bd2ff6b4b2
  includes_vendor_composer_autoload_static_php -- ref --> symbol_Composer_Autoload
  includes_vendor_composer_autoload_static_php -- ref --> symbol_Composer__InstalledVersions
  includes_vendor_composer_ClassLoader_php -- new --> symbol__Composer_Autoload_ClassLoader
  includes_vendor_composer_ClassLoader_php -- new --> symbol_namespace
  includes_vendor_composer_ClassLoader_php -- new --> symbol__InvalidArgumentException
  includes_vendor_composer_ClassLoader_php -- new --> symbol__InvalidArgumentException
  includes_vendor_composer_ClassLoader_php -- ref --> symbol_Composer_Autoload
  includes_vendor_composer_ClassLoader_php -- ref --> symbol_Composer_Autoload_ClassLoader
  includes_vendor_composer_ClassLoader_php -- ref --> symbol_Symfony_Component
  includes_vendor_composer_ClassLoader_php -- ref --> symbol_Symfony_Component
  includes_vendor_composer_ClassLoader_php -- ref --> symbol_Symfony_Component_Console
  includes_vendor_composer_InstalledVersions_php -- use --> symbol_Composer_Autoload_ClassLoader
  includes_vendor_composer_InstalledVersions_php -- use --> symbol_Composer_Semver_VersionParser
  includes_vendor_composer_InstalledVersions_php -- new --> symbol_VersionParser
  includes_vendor_composer_InstalledVersions_php -- new --> symbol__OutOfBoundsException
  includes_vendor_composer_InstalledVersions_php -- new --> symbol__OutOfBoundsException
  includes_vendor_composer_InstalledVersions_php -- new --> symbol__OutOfBoundsException
  includes_vendor_composer_InstalledVersions_php -- new --> symbol__OutOfBoundsException
  includes_vendor_composer_InstalledVersions_php -- new --> symbol__OutOfBoundsException
  includes_vendor_composer_InstalledVersions_php -- ref --> symbol_Composer_Autoload_ClassLoader
  %% truncated